"""create_initial_tables

Revision ID: fff93c01e64c
Revises: 
Create Date: 2026-07-15 21:41:49.445342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff93c01e64c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('log_source', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logentry_destination_ip'), 'logentry', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_logentry_event_timestamp'), 'logentry', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_logentry_id'), 'logentry', ['id'], unique=False)
    op.create_index(op.f('ix_logentry_log_source'), 'logentry', ['log_source'], unique=False)
    op.create_index(op.f('ix_logentry_severity'), 'logentry', ['severity'], unique=False)
    op.create_index(op.f('ix_logentry_source_ip'), 'logentry', ['source_ip'], unique=False)
    op.create_table('threatindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_value', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threat_actor', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threatindicator_id'), 'threatindicator', ['id'], unique=False)
    op.create_index(op.f('ix_threatindicator_indicator_type'), 'threatindicator', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threatindicator_indicator_value'), 'threatindicator', ['indicator_value'], unique=True)
    op.create_index(op.f('ix_threatindicator_threat_actor'), 'threatindicator', ['threat_actor'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    op.create_index(op.f('ix_alert_severity'), 'alert', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_status'), 'alert', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_status'), table_name='alert')
    op.drop_index(op.f('ix_alert_severity'), table_name='alert')
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_threatindicator_threat_actor'), table_name='threatindicator')
    op.drop_index(op.f('ix_threatindicator_indicator_value'), table_name='threatindicator')
    op.drop_index(op.f('ix_threatindicator_indicator_type'), table_name='threatindicator')
    op.drop_index(op.f('ix_threatindicator_id'), table_name='threatindicator')
    op.drop_table('threatindicator')
    op.drop_index(op.f('ix_logentry_source_ip'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_severity'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_log_source'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_id'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_event_timestamp'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_destination_ip'), table_name='logentry')
    op.drop_table('logentry')
    # ### end Alembic commands ###
