from datetime import datetime, timezone
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.db.session import get_db
from app.models.alert import Alert
from app.schemas.alert import AlertCreate, AlertResponse, AlertUpdateStatus

router = APIRouter()


@router.get("/", response_model=List[AlertResponse], summary="Retrieve security alerts")
def read_alerts(
    skip: int = 0, 
    limit: int = 100, 
    db: Session = Depends(get_db)
) -> List[AlertResponse]:
    """
    Returns active or closed alerts generated by correlation engines.
    """
    alerts = (
        db.query(Alert)
        .order_by(Alert.created_at.desc())
        .offset(skip)
        .limit(limit)
        .all()
    )
    return alerts


@router.post("/", response_model=AlertResponse, status_code=status.HTTP_201_CREATED, summary="Create new alert")
def create_alert(
    payload: AlertCreate, 
    db: Session = Depends(get_db)
) -> AlertResponse:
    """
    Manually creates a new alert instance in the database.
    """
    new_alert = Alert(
        title=payload.title,
        description=payload.description,
        severity=payload.severity,
        status=payload.status,
        assigned_to_id=payload.assigned_to_id,
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )
    db.add(new_alert)
    db.commit()
    db.refresh(new_alert)
    return new_alert


@router.patch("/{alert_id}/status", response_model=AlertResponse, summary="Update alert lifecycle status")
def update_alert_status(
    alert_id: int, 
    payload: AlertUpdateStatus, 
    db: Session = Depends(get_db)
) -> AlertResponse:
    """
    Modifies status (e.g. from NEW to RESOLVED) of an active security alert.
    """
    alert = db.query(Alert).filter(Alert.id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with id {alert_id} not found."
        )

    alert.status = payload.status
    alert.updated_at = datetime.now(timezone.utc)
    if payload.status in ["RESOLVED", "FALSE_POSITIVE"]:
        alert.closed_at = datetime.now(timezone.utc)
    else:
        alert.closed_at = None

    db.commit()
    db.refresh(alert)
    return alert
