from datetime import datetime, timezone
from typing import List, Optional
from fastapi import APIRouter, HTTPException, status
from app.schemas.alert import AlertCreate, AlertResponse, AlertUpdateStatus

router = APIRouter()

MOCK_ALERTS: List[dict] = [
    {
        "id": 1,
        "title": "Brute Force Attack Detected",
        "description": "Multiple failed SSH authentication attempts from host 203.0.113.5",
        "severity": "HIGH",
        "status": "NEW",
        "assigned_to_id": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
        "closed_at": None,
    },
    {
        "id": 2,
        "title": "Unauthorized Admin Access Attempt",
        "description": "Host 192.168.1.105 attempted unauthorized GET /admin endpoint",
        "severity": "MEDIUM",
        "status": "INVESTIGATING",
        "assigned_to_id": 1,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
        "closed_at": None,
    }
]


@router.get("/", response_model=List[AlertResponse], summary="Retrieve security alerts")
def read_alerts(skip: int = 0, limit: int = 100) -> List[AlertResponse]:
    """
    Returns active or closed alerts generated by correlation engines.
    """
    return MOCK_ALERTS[skip : skip + limit]


@router.post("/", response_model=AlertResponse, status_code=status.HTTP_201_CREATED, summary="Create new alert")
def create_alert(payload: AlertCreate) -> AlertResponse:
    """
    Manually creates a new alert instance (simulated).
    """
    new_id = len(MOCK_ALERTS) + 1
    new_alert = {
        "id": new_id,
        "title": payload.title,
        "description": payload.description,
        "severity": payload.severity,
        "status": payload.status,
        "assigned_to_id": payload.assigned_to_id,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
        "closed_at": None,
    }
    MOCK_ALERTS.append(new_alert)
    return new_alert


@router.patch("/{alert_id}/status", response_model=AlertResponse, summary="Update alert lifecycle status")
def update_alert_status(alert_id: int, payload: AlertUpdateStatus) -> AlertResponse:
    """
    Modifies status (e.g. from NEW to RESOLVED) of an active security alert.
    """
    for alert in MOCK_ALERTS:
        if alert["id"] == alert_id:
            alert["status"] = payload.status
            alert["updated_at"] = datetime.now(timezone.utc)
            if payload.status in ["RESOLVED", "FALSE_POSITIVE"]:
                alert["closed_at"] = datetime.now(timezone.utc)
            else:
                alert["closed_at"] = None
            return alert
            
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Alert with id {alert_id} not found."
    )
